---
title: "Daily Report"
output: 
  html_document:
    df_print: paged
---

```{r, include=FALSE}
library(dplyr)
library(knitr)
library(kableExtra)
library(PerformanceAnalytics)
library(quantmod)
library(tidyverse)
library(modeldata)
library(forecast)



sigtab<- function(tkr){
  spy <- getSymbols(tkr, src = "yahoo", from = Sys.Date()-100, to = Sys.Date(), auto.assign = FALSE)
  signal_RSI_B  =1*(RSI(Cl(spy))< 30)%>% replace(is.na(.), 0)
  signal_EMA1_B =1*(EMA(Cl(spy),n=12)>EMA(Cl(spy),n=26))%>% replace(is.na(.), 0)
  signal_EMA2_B =1*(EMA(Cl(spy),n=24)>EMA(Cl(spy),n=52))%>% replace(is.na(.), 0)
  signal_MACD1_B=1*(MACD(Cl(spy))$signal>0.3)%>% replace(is.na(.), 0)
  signal_MACD2_B=1*(MACD(Cl(spy), nSig = 18)$signal>0.3)%>% replace(is.na(.), 0)
  signal_BB_B=1*(BBands(Cl(spy))$pctB<0)%>% replace(is.na(.), 0)
  signal_ADX_B=1*((ADX(spy)$DIp>ADX(spy)$DIn)&ADX(spy)$ADX>0.25)%>% replace(is.na(.), 0)
  signal_B      =signal_RSI_B+signal_EMA1_B+signal_EMA2_B+signal_MACD1_B+signal_MACD2_B+signal_BB_B+signal_ADX_B
  signal_RSI_S  =1*(RSI(Cl(spy))> 70)%>% replace(is.na(.), 0)
  signal_EMA1_S =1*(EMA(Cl(spy),n=12)<EMA(Cl(spy),n=26))%>% replace(is.na(.), 0)
  signal_EMA2_S =1*(EMA(Cl(spy),n=24)<EMA(Cl(spy),n=52))%>% replace(is.na(.), 0)
  signal_MACD1_S=1*(MACD(Cl(spy))$signal<0)%>% replace(is.na(.), 0)
  signal_MACD2_S=1*(MACD(Cl(spy), nSig = 18)$signal<0)%>% replace(is.na(.), 0)
  signal_BB_S=1*(BBands(Cl(spy))$pctB>1)%>% replace(is.na(.), 0)
  signal_ADX_S=1*((ADX(spy)$DIp<ADX(spy)$DIn)&ADX(spy)$ADX>0.25)%>% replace(is.na(.), 0)
  signal_S      =signal_RSI_S+signal_EMA1_S+signal_EMA2_S+signal_MACD1_S+signal_MACD2_S+signal_BB_S+signal_ADX_S
  
  dailyreturn   =(dailyReturn(spy)%>% replace(is.na(.), 0))*100
  weeklyreturn  =(SMA(dailyReturn(spy),n=5)%>% replace(is.na(.), 0))*100

  volatility=volatility(spy,  mean0=TRUE)%>% replace(is.na(.), 0)
  ADX=ADX(spy)$ADX%>% replace(is.na(.), 0)
  
  
  Sig_Tab=cbind( signal_RSI_B  
                ,signal_EMA1_B 
                ,signal_EMA2_B 
                ,signal_MACD1_B
                ,signal_MACD2_B
                ,signal_BB_B
                ,signal_ADX_B
                ,signal_B      
                ,signal_RSI_S  
                ,signal_EMA1_S 
                ,signal_EMA2_S 
                ,signal_MACD1_S
                ,signal_MACD2_S
                ,signal_BB_S
                ,signal_ADX_S
                ,signal_S      
                ,dailyreturn   
                ,weeklyreturn
                ,volatility
                ,ADX)
  
  colnames(Sig_Tab)=cbind( "signal_RSI_B"
                           ,"signal_EMA1_B" 
                           ,"signal_EMA2_B" 
                           ,"signal_MACD1_B"
                           ,"signal_MACD2_B"
                           ,"signal_BB_B"
                           ,"signal_ADX_B"
                           ,"signal_B"      
                           ,"signal_RSI_S"  
                           ,"signal_EMA1_S" 
                           ,"signal_EMA2_S" 
                           ,"signal_MACD1_S"
                           ,"signal_MACD2_S"
                           ,"signal_BB_S"
                           ,"signal_ADX_S"
                           ,"signal_S"      
                           ,"dailyreturn"   
                           ,"weeklyreturn"
                           ,"Vol"
                           ,"ADX")
  Sig_Tab=as.data.frame(Sig_Tab)
  Sig_Tab$stock=tkr
  sig_day=tail(Sig_Tab,1)
  sig_day_change=sig_day
  sig_day_change[,]=c(1*(Sig_Tab[nrow(Sig_Tab),1:ncol(sig_day)-1] - Sig_Tab[nrow(Sig_Tab)-1,1:ncol(sig_day)-1]),tkr)
  return(list(tab=Sig_Tab,day=sig_day,change=sig_day_change))
}



```


```{r , include=FALSE}
tkrs=unique(c("DOCU","ESPO","VEEV","OKTA","CWH","TWOU","MAXR","COST","NTSX","MA","V","LUMN","BTI","CLX","TRP.TO","RSI.TO","LSPD.TO","ATE.TO","EDGE.TO","ZEO.TO","ZRE.TO","RCI-B.TO","BTO.TO","ABX.TO","NWH-UN.TO","SJR-B.TO","IHI","XEG.TO","XMA.TO","XIN.TO","XMD.TO","XIT.TO","SU.TO","MFC.TO","TRP.TO","T.TO","BEPC.TO","KL.TO","CGL.TO","SKYY","RNW.TO","PSI","ICLN","ARKK","ETHQ.TO","RSI.TO","LSPD.TO","ATE.TO","LIFE.TO","MCHI","XCH.TO","IHF","ZEO.TO","XGD.TO","ZRE.TO","HACK","RCI-B.TO","BTO.TO","ABX.TO","NWH-UN.TO","XTR.TO","XEG.TO","XMA.TO","XIN.TO","XMD.TO","XIT.TO","BIP-UN.TO","AP-UN.TO","RTH","TAN","PBD","EMQQ","KGRN","VDY.TO","ROBO","BLDP.TO","AC.TO","DGRO","BCE.TO","ATZ.TO","ARRY","ZCH.TO","REI-UN.TO","BB.TO","GNOM","ARKG","VGRO.TO","SCHD","WCN.TO","RBA.TO","VRE.TO","XDSR.TO","BEP-UN.TO","XEQT.TO","XQQ.TO","VFV.TO","CNR.TO","XUH.TO","XUU.TO","PSI","IGV","PSJ","SOXX","IHI","IVW","XST.TO","XUT.TO","CPX.TO","HXS.TO","HXQ.TO","XHC.TO","BNS.TO","TD.TO","ENB.TO","CNQ.TO","RY.TO","CSIQ","PLTR","TGT","BMO","C","BTI","ETHQ.TO","RSI.TO","GDNP.V","LSPD.TO","ATE.TO","EDGE.TO","ZEO.TO","ZRE.TO","RCI-B.TO","BTO.TO","ABX.TO","NWH-UN.TO","SJR-B.TO","IHI","XEG.TO","XMA.TO","XIN.TO","XMD.TO","XIT.TO","SU.TO","MFC.TO","TRP.TO","T.TO","BEPC.TO","KL.TO","CGL.TO","SKYY","RNW.TO","PSI","ICLN","HEO.V","ARKK","BNS.TO","TD.TO","ENB.TO","CNQ.TO","RY.TO","CSIQ","PLTR","TGT","BMO","C","BTI","ETHQ.TO","RSI.TO","GDNP.V","LSPD.TO","ATE.TO","IPA.V","LIFE.TO","MCHI","XCH.TO","IHF","ZEO.TO","XGD.TO","ZRE.TO","HACK","RCI-B.TO","BTO.TO","ABX.TO","NWH-UN.TO","XTR.TO","XEG.TO","XMA.TO","XIN.TO","XMD.TO","XIT.TO","BIP-UN.TO","AP-UN.TO","RTH","TAN","PBD","EMQQ","KGRN","VDY.TO","ROBO","BLDP.TO","AC.TO","DGRO","BCE.TO","ATZ.TO","ARRY","ZCH.TO","REI-UN.TO","BB.TO","GNOM","ARKG","VGRO.TO","SCHD","WCN.TO","RBA.TO","VRE.TO","XDSR.TO","BEP-UN.TO","XEQT.TO","XQQ.TO","VFV.TO","CNR.TO","XUH.TO","XUU.TO","PSI","IGV","PSJ","SOXX","IHI","IVW","XST.TO","XUT.TO","CPX.TO","HXS.TO","HXQ.TO","XHC.TO")
)

TKRS=map(tkrs,sigtab)
day_tab=c()
for (i in 1:length(TKRS)) {
  x=TKRS[[i]]$day
  day_tab=rbind(x,day_tab)
}

change_tab=c()
for (i in 1:length(TKRS)) {
  x=TKRS[[i]]$change
  change_tab=rbind(x,change_tab)
}
 url=paste("https://finance.yahoo.com/quote/",day_tab$stock,sep = "")
 urls <- paste0("<a href='",url,"'>",url,"</a>")
 #urls
```

# Buy

```{r, echo=FALSE, eval=FALSE}
day_tab %>% 
   mutate(urlls = cell_spec(stock, "html", link = url)) %>%
   arrange(desc(signal_B),desc(weeklyreturn))%>%
  head(20)%>%
   kable("html", escape = FALSE) %>%
   kable_styling(bootstrap_options = c("hover", "condensed"))
```

# Sell

```{r, echo=FALSE, eval=FALSE}
day_tab %>% 
   mutate(urlls = cell_spec(stock, "html", link = url)) %>%
   arrange(desc(signal_S),weeklyreturn)%>%
  head(20)%>%
   kable("html", escape = FALSE) %>%
   kable_styling(bootstrap_options = c("hover", "condensed"))
```

# Buy change

```{r, echo=FALSE, eval=FALSE}
change_tab %>% 
   mutate(urlls = cell_spec(stock, "html", link = url)) %>%
   arrange(desc(signal_B),desc(weeklyreturn))%>%
  head(20)%>%
   kable("html", escape = FALSE) %>%
   kable_styling(bootstrap_options = c("hover", "condensed"))
```

# Sell change

```{r, echo=FALSE, eval=FALSE}
change_tab %>% 
   mutate(urlls = cell_spec(stock, "html", link = url)) %>%
   arrange(desc(signal_S),weeklyreturn)%>%
  head(20)%>%
   kable("html", escape = FALSE) %>%
   kable_styling(bootstrap_options = c("hover", "condensed"))
```

# day_tab

```{r}
day_tab %>% 
   mutate(urlls = cell_spec(stock, "html", link = url))%>%
   arrange(desc(signal_B),desc(ADX))%>%
    DT::datatable(, escape = FALSE)
```

# change_tab

```{r}
change_tab %>% 
   mutate(urlls = cell_spec(stock, "html", link = url)) %>%
   arrange(desc(signal_B),desc(ADX))%>%
DT::datatable(, escape = FALSE)
```

